### ISSUE TITLE
Error when starting tuifi

### ISSUE THREAD

**Issue by Sigmanificient** [GiorgosXou/TUIFIManager#53]
**os**: Arch GNU/Linux
**version**: Latest commit from git

When starting TUIFIManager using the command provided from setup.py in a local installation, it crashes with the following error:
```
(venv) [sigmanificient@Sigmachine TUIFIManager]$ tuifi
Traceback (most recent call last):
  File "/home/sigmanificient/TUIFIManager/venv/bin/tuifi", line 33, in <module>
    sys.exit(load_entry_point('TUIFIManager', 'console_scripts', 'tuifi')())
  File "/home/sigmanificient/TUIFIManager/venv/bin/tuifi", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sigmanificient/TUIFIManager/TUIFIManager/__init__.py", line 11, in <module>
    from       .TUIMenu import    *
  File "/home/sigmanificient/TUIFIManager/TUIFIManager/TUIMenu.py", line 3, in <module>
    from TUItilities import BEGIN_MOUSE,END_MOUSE
ModuleNotFoundError: No module named 'TUItilities'
```

This is caused by the line 3 from `TUIFile.py`:
```py
from TUItilities import BEGIN_MOUSE,END_MOUSE
```

**Comment by GiorgosXou** [comment]
oh i forgot the dot, thanks for the catch

**Comment by GiorgosXou** [comment]
That  line was a test, it is not needed anymore

**Comment by Sigmanificient** [comment]
Yes, but still a bug for now
