### ISSUE TITLE
Expecting pdcurses at: C:\Users\USER\scoop\persist\python\Lib\site-packages\unicurses/64 bit binaries/pdcdllu/pdcurses.dll

### ISSUE THREAD

**Issue by graphixillusion** [GiorgosXou/TUIFIManager#85]
## *Specifications*
- OS: `Windows 11 x64`
- Terminal: `Windows Terminal`
- TUIFI Version: `v.3.3.1` 

## *Describe the bug*
Expecting pdcurses at: C:\Users\USER\scoop\persist\python\Lib\site-packages\unicurses/64 bit binaries/pdcdllu/pdcurses.dll

## *Additional context*
I have installed this with python which was installed with scoop under Windows 11 x64. The program's ui starts and i can navigate: the simple operations works good like cut, paste, move, even shift tab works but for example if i hit ctrl +e it will exit to the prompt with the above message. Even tuifi --version shows this error. I've also checked if the pdcurses.dll file is present in the specified path and the file is there so i don't know what's going on...

**Comment by GiorgosXou** [comment]
Just remove this [line](https://github.com/unicurses/unicurses/issues/24#issuecomment-1676259561), it's just a `print(...)` I forgot to remove. lol

**Comment by graphixillusion** [comment]
@GiorgosXou But the CTRL+E shoudn't exit to the prompt in the current directory selected in the gui?

**Comment by GiorgosXou** [comment]
Although not mentioned [this trick](https://stackoverflow.com/a/16694919/11465149) is not supported [for windows](https://github.com/GiorgosXou/TUIFIManager/blob/86bac184db9faddeccbf4d74a348ce517603650b/TUIFIManager/TUItilities.py#L37) at the momment

**Comment by GiorgosXou** [comment]
***Awaits testing:***
https://github.com/GiorgosXou/TUIFIManager/commit/0b3fffcdb33dd6b4997c7325a17261a60cfe7fb1

**Comment by graphixillusion** [comment]
> [0b3fffc](https://github.com/GiorgosXou/TUIFIManager/commit/0b3fffcdb33dd6b4997c7325a17261a60cfe7fb1) _**Awaits testing on windows**_

The last version crashes on start with this error on Windows

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\USER\scoop\apps\python\current\Scripts\tuifi.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\USER\scoop\apps\python\current\Lib\site-packages\TUIFIManager\__main__.py", line 46, in main
    fileManager  = TUIFIManager(0,0, HEIGHT,WIDTH, (True,True,True,True), **args, is_focused=True)
  File "C:\Users\USER\scoop\apps\python\current\Lib\site-packages\TUIFIManager\__init__.py", line 155, in __init__
    if stty_a('^Z')               : signal.signal(signal.SIGTSTP, self.suspend_proccess)
                                                  ^^^^^^^^^^^^^^
AttributeError: module 'signal' has no attribute 'SIGTSTP'

```

**Comment by GiorgosXou** [comment]
@graphixillusion I just installed python `3.13.1` with tuifi `5.0.5` on windows 11 and I haven't had any issue running it. Do you use WSL by any chance? Or how did you install it?

**Comment by GiorgosXou** [comment]
Also, what terminal do you use?

**Comment by graphixillusion** [comment]
tuifi --version
TUIFIManager v.5.0.5 | Powered by UNI-CURSES

python --version
Python 3.13.1

I'm using windows terminal under Windows 11 24h2

**Comment by GiorgosXou** [comment]
did you install it via `pip` or via some other way?

**Comment by graphixillusion** [comment]
yes i have installed via pip

**Comment by GiorgosXou** [comment]
Weird but ok, i'll try a fix and push a new version in a few minutes, let me know if it works

**Comment by graphixillusion** [comment]
version 5.0.7 works good, but ctrl+e still doesn't work

**Comment by GiorgosXou** [comment]
For ctl+e to work, you need to configure your own ".bashrc equivalent for windows" based on this [script for Linux](https://github.com/GiorgosXou/TUIFIManager/blob/master/etc/tuifi_cd.sh) *(I haven't had the time to do so, therefore feel free to do so if you want  and make a pull request [shouldn't be hard])*
